name: ala_pos
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+9

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.2.0
  bloc: ^8.0.3
  built_collection: ^5.1.1
  connectivity_plus: ^2.3.3
  core:
    path: packages/core
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  floor: ^1.3.0
  flutter:
    sdk: flutter
  # flutter_localizations: # Add this line
  #   sdk: flutter 
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5
  # form_builder_validators: ^8.1.1
  formz: ^0.4.1
  flutter_multi_formatter: ^2.5.7
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  hooked_bloc: ^1.2.0
  injectable: ^1.5.3
  ionicons: ^0.1.2
  intl: ^0.17.0
  json_annotation: ^4.5.0
  open_file: ^3.2.1
  permission_handler: ^10.0.0
  simple_animations: ^4.0.2
  sizer: ^2.0.15
  share_plus: ^4.0.10
  uuid: ^3.0.6
  flutter_barcode_scanner: ^2.0.0
  flutter_beep: ^1.0.0
  flutter_blue_plus: ^1.2.0
  esc_pos_utils: ^1.1.0
  flutter_esc_pos_utils: ^0.1.7

dev_dependencies:
  auto_route_generator: ^4.2.1
  build_runner: ^2.2.0
  floor_generator: ^1.3.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.10.0
  # analyzer: ^4.4.0


dependency_overrides:
  analyzer: ^4.4.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/empty/
    - .env
    - .env.production
    - .env.android.emulator
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # pub global activate rename

  # pub global run rename --bundleId com.onatcipli.networkUpp
  # pub global run rename --appname "Network Upp"
  # rename --appname yourappname -t ios
  # pub global run rename --bundleId com.example.android.app --target android
